name:  Deployment in ArgoCD

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build --file Dockerfile1 -t ${{ secrets.DOCKERHUB_USERNAME }}/webproject:latest .

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webproject:latest

      - name: Show deployment.yaml before replacement
        run: cat deployment.yaml

      - name: Replace image tag in manifest
        run: |
          sed -i "s|image: chndra/webproject:.*|image: chndra/webproject:${{ github.sha }}|" deployment.yaml

      - name: Show deployment.yaml after replacement
        run: cat deployment.yaml

      - name: Set up Git user and remote using PAT
        run: |
         git config user.name "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}


      - name: Auto-commit updated manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: "Update image tag to ${{ env.IMAGE_TAG }}"
         file_pattern: deployment.yaml


